name: fastddsspy_dependencies_ubuntu
description: Common first step for all Fast DDS Spy jobs. It checkout repository, downloads dependencies and install required packages.

inputs:

  ubuntu_version:
    description: Specify runs-on machine to download specific artifact
    required: true

  dependencies_artifact_postfix:
    description: Specify artifact postfix in case it wants to use a manual one
    required: false
    default: _nightly

  target_workspace:
    description: Specify directory to download dependencies
    required: false
    default: './install'

runs:
  using: composite
  steps:

    - name: Install Fast DDS dependencies
      uses: jparisu/eProsima-CI/ubuntu/install_fast_dependencies@main

    - name: Install yaml cpp dependency
      uses: jparisu/eProsima-CI/ubuntu/install_yamlcpp@main

    - name: Download dependencies artifact
      uses: jparisu/eProsima-CI/ubuntu/download_dependency@main
      with:
        artifact_name: built_ddspipe_${{ inputs.ubuntu_version }}${{ inputs.dependencies_artifact_postfix }}
        workflow_source: build_ddspipe.yml
        workflow_source_repository: jparisu/eProsima-CI
        target_workspace: ${{ inputs.target_workspace }}
