# Nightly test workflow for Fast DDS Spy
name: nightly-windows-ci

on:
  workflow_dispatch:

  schedule:
    - cron: '0 5 * * *'

jobs:

  reusable_windows_tests_v2:
    name: reusable_windows_tests_v2
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      custom_version_build: 'v2'
      dependencies_artifact_postfix: '_nightly'
      ref: '0.x'
    secrets: inherit

  reusable_windows_tests_v3:
    name: reusable_windows_tests_v3
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      custom_version_build: 'v3'
      dependencies_artifact_postfix: '_nightly'
      ref: 'ci/test-reporting'
    secrets: inherit
