# Reusable workflow to run the following jobs:
#
#   - multiplatform-tests
#     - [ ubuntu-22.04 | ubuntu-24.04 | windows-2019 | windows-2022 ]
#     - [ Debug | Release ]
#     - execute tests in different versions of ubuntu with different build types
#
#   - asan
#     - ubuntu-22.04
#     - execute tests with ASAN flag
#
#   - tsan
#     - ubuntu-22.04
#     - execute tests with TSAN flag
#
#   - clang
#     - ubuntu-22.04
#     - execute clang-tidy check
#
#   - coverage
#     - ubuntu-22.04
#     - execute test with coverage flag and upload results
#
#   - flaky
#     - ubuntu-22.04
#     - execute flaky tests
#
#   - uncrustify
#     - ubuntu-22.04
#     - test uncrustify
#
#   - python-linter
#     - ubuntu-22.04
#     - test python linter
#

name: reusable-workflow

on:

  workflow_call:
    inputs:

      custom_version_build:
        description: >
          Version of Fast DDS build from eProsima-CI.
        required: true
        type: string

      dependencies_artifact_postfix:
        description: 'Postfix name to add to artifact name to download dependencies. This is use to download a specific artifact version from eProsima-CI.'
        required: true
        default: '_nightly'
        type: string

      ref:
        description: >
          The branch or tag name to checkout.
        required: true
        type: string
        default: 'main'

      os:
        description: 'Specify runs-on machine to download specific artifact'
        required: true
        type: string

env:
  code_packages_names: 'fastddsspy_participants fastddsspy_yaml fastddsspy_tool'
  docs_packages_names: 'fastddsspy_docs'

jobs:


#####################################################################
# MULTIPLATFORM TEST

  multiplatform-tests:
    name: ${{ inputs.os }}-ci-${{ matrix.cmake_build_type }}
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        cmake_build_type:
          - Release
          - Debug

    steps:

      - name: Sync repository
        uses: eProsima/eProsima-CI/external/checkout@feature/test-reporting
        with:
          path: src
          ref: ${{ inputs.ref }}

      - name: Download dependencies and install requirements
        uses: ./src/.github/actions/project_dependencies
        with:
          os: ${{ inputs.os }}
          cmake_build_type: ${{ matrix.cmake_build_type }}
          custom_version_build: ${{ inputs.custom_version_build }}
          dependencies_artifact_postfix: ${{ inputs.dependencies_artifact_postfix }}
          secret_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile and run tests
        id: compile_and_test
        uses: eProsima/eProsima-CI/multiplatform/colcon_build_test@feature/test-reporting
        with:
          packages_names: ${{ env.code_packages_names }}
          cmake_args: -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }}
          workspace_dependencies: './install'
          ctest_args: --label-exclude "xfail"
          colcon_meta_file: ./src/.github/workflows/configurations/${{ runner.os }}/colcon.meta
          test_report_artifact: test_report${{ inputs.dependencies_artifact_postfix }}_${{ inputs.custom_version_build }}_${{ inputs.os }}_${{ matrix.cmake_build_type }}

      - name: Test Report
        uses: eProsima/eProsima-CI/external/test-reporter@feature/test-reporting
        if: success() || failure()
        with:
          name: "Report: ${{ matrix.os }} | ${{ matrix.cmake_build_type }} "
          path: "${{ steps.compile_and_test.outputs.ctest_results_path }}*.xml"
          working-directory: 'src'
          path-replace-backslashes: 'true'
          list-tests: 'failed'


